[package]
name = "lang-learn-native-prototype"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
name = "lang_learn_native_prototype_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.7.1", features = [] }

[dependencies]
tauri = { version = "=2.12.1", features = [] }
serde = { version = "=1.0.229", features = ["derive"] }
sqlx = { version = "=0.8.6", default-features = false, features = ["runtime-tokio", "sqlite"] }
