/**
 * 從既有題庫產生可離線的分級資源與小型筆數索引；來源仍以手寫批次為準。
 * --check 只核對，不寫入；生成器只能覆寫自己帶標記的固定輸出檔。
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';

const output = new URL('../assets/js/data/catalog/', import.meta.url);
const marker = '// Generated by tools/build-catalog.mjs; do not edit.\n';
const files = new Map();
const metadata = {};
const serial = row => Number(row.id.slice(row.id.lastIndexOf('-') + 1));
const counts = rows => Object.fromEntries([1, 2, 3, 4, 5].map(level => [level, rows.filter(row => row.level === level).length]));
const digest = value => createHash('sha256').update(JSON.stringify(value)).digest('hex');

for (const lang of ['en', 'ja']) {
  const read = async kind => (await import(new URL(`../assets/js/data/${lang}/${kind}.js`, import.meta.url)))[kind];
  const words = await read('words');
  const sentences = await read('sentences');
  const readings = await read('readings');
  const scenes = lang === 'ja' ? await read('scenes') : [];
  if (!words.every((word, index) => Number.isFinite(serial(word)) && (!index || serial(words[index - 1]) < serial(word)))) {
    throw new Error('題庫順序已不符合穩定流水號，請明確更新 catalog 順序政策，不可靜默重排。');
  }
  const questions = readings.flatMap(passage => passage.questions.map(q => ({ ...q, level: passage.level })));
  metadata[lang] = { words: words.length, sentences: sentences.length, scenes: scenes.length,
    readings: readings.length, readingQuestions: questions.length,
    wordsByLevel: counts(words), sentencesByLevel: counts(sentences), scenesByLevel: counts(scenes),
    readingQuestionsByLevel: counts(questions), sourceHash: digest({ words, sentences, scenes, readings }) };
  for (const level of [1, 2, 3, 4, 5]) files.set(`${lang}-words-${level}.js`, ['words', words.filter(w => w.level === level)]);
  for (const [kind, rows] of Object.entries({ sentences, scenes, readings })) files.set(`${lang}-${kind}.js`, [kind, rows]);
}
files.set('meta.js', ['CATALOG_META', metadata]);
const check = process.argv.includes('--check');
if (!check) await mkdir(output, { recursive: true });
for (const [name, [key, value]] of files) {
  const credit = name.startsWith('en-words-')
    ? '// NGSL/TSL-derived records: CC BY-SA 4.0; other records retain their source license. See CREDITS.md.\n'
    : '// Source attribution and licensing: see CREDITS.md.\n';
  let body;
  if (key === 'words') {
    const keys = ['id', 'zh', 'target', 'reading', 'romaji', 'pos', 'category', 'level'];
    if (!value.every(row => Object.keys(row).length === keys.length && keys.every(field => Object.prototype.hasOwnProperty.call(row, field)))) {
      throw new Error('單字欄位已變動，請更新 tuple 格式，不可靜默遺失欄位。');
    }
    const nullReadings = value.every(row => row.reading === null && row.romaji === null);
    const fields = keys.filter(key => key !== 'level' && (!nullReadings || !['reading', 'romaji'].includes(key)));
    const level = Number(name.slice(-4, -3)), prefix = name.slice(0, 2) + '-w-';
    if (!value.every(row => row.id === prefix + String(serial(row)).padStart(3, '0') && row.level === level)) throw new Error('ID 或級別格式不可安全重建。');
    const tuples = value.map(row => fields.map(field => field === 'id' ? serial(row) : row[field]));
    body = `const keys=${JSON.stringify(fields)},rows=${JSON.stringify(tuples)};\nexport const words=rows.map(row=>({...Object.fromEntries(keys.map((key,index)=>[key,key==='id'?${JSON.stringify(prefix)}+String(row[index]).padStart(3,'0'):row[index]])),level:${level}${nullReadings ? ',reading:null,romaji:null' : ''}}));\n`;
  } else body = `export const ${key} = ${JSON.stringify(value)};\n`;
  const text = marker + credit + body;
  const path = new URL(name, output);
  let previous;
  try { previous = await readFile(path, 'utf8'); } catch (error) { if (error.code !== 'ENOENT') throw error; }
  if (check) {
    if (previous !== text) throw new Error(`catalog 與原題庫不同，請重新生成：${name}`);
  } else {
    if (previous !== undefined && !previous.startsWith(marker)) throw new Error(`拒絕覆寫非生成檔：${name}`);
    await writeFile(path, text);
  }
}
console.log(`${check ? 'PASS' : '已生成'} catalog：${files.size} 個固定資源，ID／順序／授權可追溯。`);
